---
title: "2023-10-27 11AM"
---

## What was affected

* Documentation Prod (This site)
* Documentation Dev (Internal Dev)
* CV Site ([bradley.breadnet.co.uk](https://bradley.breadnet.co.uk))

## What caused it

Fly have started charging for IPV4 and because I live in a badly managed country, I have to save all my money for things
like power bills, and petrol

I released the dedicated IPV4 address' under the assumption the `*.fly.io` domain would not require an IP address on the app,
and instead use routing internally.

This was not the case. As soon as I revoked the IP address, and the CloudFlare cache was up for _renewal_, the site was down

## What monitoring was in place

Uptime robot is configured to monitor the below sites that were affected

* [Documentation Production](https://status.breadnet.co.uk/793304791)
* [Portfolio](https://status.breadnet.co.uk/795270918)

!!! note "Dev is not here"
    I do not monitor Dev, this environment is just to check formatting etc

* At 10:49 AM British time an alert was posted by UptimeRobot that `:red_circle:  Incident started on breadNET Documentation`
* At 10:50 AM British time an alert was posted by UptimeRobot that `:red_circle:  Incident started on Profile`
* At 11:28 AM British Time I requested a shared IP
* At 11:31 AM British time an alert was posted by UptimeRobot that `:large_green_circle: Incident resolved on breadNET Documentation`
* At 11:31 AM British time an alert was posted by UptimeRobot that `:large_green_circle: Incident resolved on Profile`


## What was done to resolve it

Shared IP assigned to applications affected


* KB: [Release IP address fly](../cloud/fly/fly-release-ip-address.md#assign-shared-ip)

## What did we learn

* Test a single site at a time
* Fly does not do backend proxying with no IP address and their own managed DNS
